---
title: "Gradients FA Summary"
author: "CTELab"
format: 
  revealjs:
    theme: night
    code-fold: true
editor: visual
incremental: true
---

```{r}

library(tidyverse) # data cleanup
library(viridis) # color palette
library(ggfortify) # PCA visualizations
library(ggforce) # added ggplot functions
library(vegan) # multivariate analyses

# load in all data
all_species <- read_csv("Data/Biomarkers/FattyAcids/gradients2019_corespecies_FA_QAQC.csv")
# subset inverts
all_inverts <- all_species %>%
          filter(type == "invert")
# subset algae
all_algae <- all_species %>%
          filter(type == "algae")
# Create simplified long dataset for analysis of algae
long_algae <- all_algae %>%
  select(FAsampleName, `NIC-Klein-Midpoint-Annual`, genusSpecies, `8:0`:`22:4w3`) %>%
  pivot_longer(cols = `8:0`:`22:4w3`, names_to = 'FA', values_to = 'proportion')
 # pivot algae data wide for PCA/nMDS
 grad_conc_wide <- long_algae %>%
   select(FA, genusSpecies, proportion, `NIC-Klein-Midpoint-Annual`, FAsampleName) %>%
   pivot_wider(names_from = FA, values_from = proportion, values_fill = 0)
 # Create simplified long dataset for analysis of inverts
long_inverts <- all_inverts %>%
  select(FAsampleName, genusSpecies, `NIC-Klein-Midpoint-Annual`, `8:0`:`22:4w3`) %>%
  pivot_longer(cols = `8:0`:`22:4w3`, names_to = 'FA', values_to = 'proportion')
 # pivot invert data wide for PCA/nMDS
 grad_invert_wide <- long_inverts %>%
   select(FA, genusSpecies, proportion, FAsampleName, `NIC-Klein-Midpoint-Annual`) %>%
   pivot_wider(names_from = FA, values_from = proportion, values_fill = 0)

```

## Sample Processing

-   Invertebrate Samples

    -   559 of 559 complete

    -   15 sites

    -   11 species

    -   

        ```{r}

        list(unique(all_inverts$genusSpecies))

        ```

## Sample Processing

-   Algal Samples

    -   106 of 155 complete

        -   remaining chromatograms in progress

    -   13 sites

    -   7 species
    
    -   

        ```{r}

        list(unique(all_algae$genusSpecies))

        ```
    
## nMDS - Inverts

```{r, error = FALSE, warning = FALSE, message = FALSE}

# select EPA, ARA, SDA, PAL, OLE, LIN, VAC, and dominant sats (16, 18) 
sub_wide <- grad_invert_wide %>% # fix 16:0 error in inverts
  select(genusSpecies, FAsampleName, "14:0", "16:0", "16:1w7c", "18:0", "18:1w7c", "18:3w3", "18:4w3c", "18:1w9c", "20:4w6", "20:5w3")
sub_wide_trans <- (sub_wide[,3:12])
sub_wide_trans <- bind_cols(sub_wide[1:2], sub_wide_trans)

batch_1_2_MDS <- metaMDS(sub_wide_trans[3:12], autotransform = TRUE, distance = "clark", trace = FALSE)
batch_1_2_MDS_points <- batch_1_2_MDS$points
batch_1_2_MDS_points <- data.frame(batch_1_2_MDS_points)
plot_data_batch_1_2 <- data.frame(batch_1_2_MDS_points, sub_wide[,1])


plot_data_batch_1_2 %>%
ggplot(aes(MDS1, MDS2, color = genusSpecies)) +
  geom_point(size = 2) + # set size of points to whatever you want
  scale_color_viridis(discrete = TRUE, end = 0.9, option = 'C') + # my favorite color-blind and b&w friendly palette, look at the viridis package for more details
   geom_mark_hull(expand = unit(1, "mm"), radius = unit(1, "mm"), concavity = 5)  + # optional 'hulls' around points
  theme_void()  # optional, I just like this theme



```

## PCA - Inverts

```{r, error = FALSE, warning = FALSE, message = FALSE}

 # remove zero columns
 grad_conc_PCA <- grad_invert_wide %>%
   select(where(~ any(. != 0)))
 # run PCA
PCA_results <-  prcomp(grad_conc_PCA[,c(4:65)], scale = TRUE)
PCA_results$rotation <- -1*PCA_results$rotation
#reverse the signs of the scores
PCA_results$x <- -1*PCA_results$x



autoplot(PCA_results, data = grad_conc_PCA, colour = 'genusSpecies', 
         size = 4,
         loadings = TRUE, 
         loadings.colour = 'grey', 
         loadings.label = TRUE, 
         loadings.label.size = 4) +
  scale_color_viridis(discrete = TRUE, option = "C") +
  theme_minimal()


```
## FA Gradient - Inverts

```{r, fig.width=5.2, fig.height=7, fig.align='center'}

invert_grad <- grad_invert_wide %>%
  select(genusSpecies, `NIC-Klein-Midpoint-Annual`, '14:0', '16:0', '16:1w7c', '18:0', '18:3w6', '20:0', '20:4w6', '22:0') %>%
  filter(genusSpecies %in% c("Prostebbingia gracilis", "Dendrilla membranosa", "Gondogeneia antarctica"))
invert_grad_long <- invert_grad %>%
  pivot_longer(cols = `14:0`:`22:0`, names_to = 'FA', values_to = 'proportion')

  
invert_grad_long %>%
  ggplot(aes(`NIC-Klein-Midpoint-Annual`, proportion)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  facet_grid(FA ~ genusSpecies, scales = 'free')


```


## nMDS - Algae

```{r, error = FALSE, warning = FALSE, message = FALSE}

# select EPA, ARA, SDA, PAL, OLE, LIN, VAC, and dominant sats (16, 18) 
sub_wide <- grad_conc_wide %>% # fix 16:0 error in inverts
  select(genusSpecies, FAsampleName, "14:0", "16:0", "16:1w7c", "18:0", "18:1w7c", "18:3w3", "18:4w3c", "18:1w9c", "20:4w6", "20:5w3")
sub_wide_trans <- (sub_wide[,3:12])
sub_wide_trans <- bind_cols(sub_wide[1:2], sub_wide_trans)

batch_1_2_MDS <- metaMDS(sub_wide_trans[3:12], autotransform = TRUE, distance = "clark", trace = FALSE)
batch_1_2_MDS_points <- batch_1_2_MDS$points
batch_1_2_MDS_points <- data.frame(batch_1_2_MDS_points)
plot_data_batch_1_2 <- data.frame(batch_1_2_MDS_points, sub_wide[,1])

plot_data_batch_1_2 %>%
ggplot(aes(MDS1, MDS2, color = genusSpecies)) +
  geom_point(size = 2) + # set size of points to whatever you want
  scale_color_viridis(discrete = TRUE, end = 0.9, option = 'D') + # my favorite color-blind and b&w friendly palette, look at the viridis package for more details
   geom_mark_hull(expand = unit(1, "mm"), radius = unit(1, "mm"), concavity = 5)  + # optional 'hulls' around points
  theme_void()  # optional, I just like this theme

```

## PCA - Algae

```{r, error = FALSE, warning = FALSE, message = FALSE}

 # remove zero columns
 grad_conc_PCA <- grad_conc_wide %>%
   select(where(~ any(. != 0)))
 # run PCA
PCA_results <-  prcomp(grad_conc_PCA[,c(4:67)], scale = TRUE)
PCA_results$rotation <- -1*PCA_results$rotation
#reverse the signs of the scores
PCA_results$x <- -1*PCA_results$x



autoplot(PCA_results, data = grad_conc_PCA, colour = 'genusSpecies', 
         size = 4,
         loadings = TRUE, 
         loadings.colour = 'grey', 
         loadings.label = TRUE, 
         loadings.label.size = 4) +
  scale_color_viridis(discrete = TRUE) +
  theme_minimal()


```

## FA Gradient - Algae

```{r, fig.width=5.2, fig.height=7, fig.align='center'}

algal_grad <- grad_conc_wide %>%
  select(genusSpecies, `NIC-Klein-Midpoint-Annual`, '14:0', '16:0', '16:1w7c', '18:0', '18:4w3c', '20:4w6', '20:5w3') %>%
  filter(genusSpecies %in% c("Desmarestia menziesii", "Phyllophora antarctica", "Himantothallus grandifolius"))
algal_grad_long <- algal_grad %>%
  pivot_longer(cols = `14:0`:`20:5w3`, names_to = 'FA', values_to = 'proportion')

  
algal_grad_long %>%
  ggplot(aes(`NIC-Klein-Midpoint-Annual`, proportion)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  facet_grid(FA ~ genusSpecies, scales = 'free')
  
  

```
